name: tdd_clean_arch
description: Deep dive into TDD and Clean Architecture in Flutter.

publish_to: "none"

version: 1.0.0+1

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  build: $runner build
  watch: $clean & $get & $runner watch
  build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  data_connection_checker: ^0.3.4
  http: ^0.12.0
  shared_preferences: ^0.5.12+4
  flutter_bloc: ^0.21.0
  dartz: ^0.9.2
  equatable: ^1.2.6
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.4
  modular_codegen:
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
